# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         mysql-genocide
version:      0.03
version_from: mysql-genocide
installdirs:  site
requires:
    DBD::mysql:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
